apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: products-api-backend
  template:
    metadata:
      labels:
        component: products-api-backend
    spec:
      containers:
        - name: products-api-app
          image: asemikitm/store-backend:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-cluster-ip-service
            - name: MYSQL_USERNAME
              value: admin
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DATABASE
              value: mysql_db
            - name: RABBITMQ_HOST
              value: rabbitmq-cluster-ip-service
            - name: RABBITMQ_PORT
              value: "5672"