version: '3.1'
services:
  notification-api:
    build:
      context: ./notifications-api
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - mysql

  products-api:
    build:
      context: ./products-api
    command: [ "java", "-jar", "/app/build/libs/products-api-0.0.1-SNAPSHOT.jar" ]
    env_file:
      - .env
    ports:
      - "8080:8080"

    depends_on:
      - rabbitmq
      - mysql

  store-frontend:
    build:
      context: ./store-frontend
    ports:
      - "3000:3000"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mysql:
    image: "mysql:8.0"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8180:8180'
volumes:
  rabbitmq-data:
  mysql-data: